### ISSUE TITLE
Performans hakkında

### ISSUE THREAD

**Issue by sametoz** [alicommit-malp/Dotnet-Core-Request-Body-Peeker#2]
Selamlar, bu eklentinin performans açısından maliyeti nedir? 

Hikayem şu, kullanıcıların POST ve GET işlemlerinde, client'tan gelen payloadı okumam gerekiyor. (bunu kayıt altına alıyorum) İşlem geçmişini tutmak adına böyle bir yöntem düşündüm. Sizce daha tasarruflu bir yolu var mıdır?

**Comment by alicommit-malp** [comment]
It really depends on your payload size.
use the BpdyPeeker in a  middleware before the MVC middleware to read the body then await next RequestDelegate and after the await use a logic to store the body's data, at this point you will have a chance to log the repose as well.
